# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_status',
            field=models.BooleanField(default=True),
        ),
    ]
