# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 02:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20170814_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
