# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_cate_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='cate',
            name='cate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
