# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_cate_cate_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_cate',
            new_name='cate',
        ),
    ]
