# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20170814_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(max_length=250)),
                ('slide_src', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('slide_link', models.CharField(max_length=250)),
            ],
        ),
    ]
