# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_title', models.CharField(max_length=250)),
                ('featured_src', models.FileField(upload_to='featured/%Y/%m/%d/')),
                ('featured_desc', models.CharField(max_length=250)),
                ('featured_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_src',
            field=models.FileField(upload_to='slides/%Y/%m/%d/'),
        ),
    ]
