# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20170814_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='featured_type',
            field=models.IntegerField(choices=[(1, '特色项目'), (2, '特色跨栏')], default=1),
        ),
    ]
