# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_featured_featured_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=250)),
                ('config_value', models.CharField(max_length=250)),
            ],
        ),
    ]
