# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=250)),
                ('menu_link', models.CharField(max_length=250)),
                ('menu_src', models.FileField(blank=True, upload_to='icon/%Y/%m/%d/')),
                ('menu_desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
