# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_recommend',
            field=models.BooleanField(default=False, verbose_name='page_status'),
        ),
    ]
