# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_post_post_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_excerpt',
            field=models.TextField(verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_recommend',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.BooleanField(default=True, verbose_name='是否发布'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
