# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20170816_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '文章', 'verbose_name_plural': '管理文章'},
        ),
    ]
